export declare const schemaRegistry: {
    readonly manifest: "schemas/manifest.schema.json";
    readonly project: "schemas/project.schema.json";
    readonly binder: "schemas/binder.schema.json";
    readonly timeline: "schemas/timeline.schema.json";
    readonly milestones: "schemas/milestones.schema.json";
    readonly historyRepair: "schemas/history-repair.schema.json";
    readonly exportProfile: "schemas/export-profile.schema.json";
    readonly previewProfileBinding: "schemas/preview-profile-binding.schema.json";
    readonly paginatedPreview: "schemas/paginated-preview.schema.json";
    readonly pageBreakMap: "schemas/page-break-map.schema.json";
    readonly appPreviewSettings: "schemas/app-preview-settings.schema.json";
    readonly citationProfile: "schemas/citation-profile.schema.json";
    readonly citationLibrary: "schemas/citation-library.schema.json";
    readonly researchNote: "schemas/research-note.schema.json";
    readonly researchLinkMap: "schemas/research-link-map.schema.json";
    readonly pdfLibrary: "schemas/pdf-library.schema.json";
    readonly sharePackageManifest: "schemas/share-package-manifest.schema.json";
    readonly privacyInventory: "schemas/privacy-inventory.schema.json";
    readonly tutorialScript: "schemas/tutorial-script.schema.json";
    readonly pluginManifest: "schemas/plugin-manifest.schema.json";
};
export type SchemaName = keyof typeof schemaRegistry;
