import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'

const generatedFilePath = resolve(process.cwd(), 'packages/schemas/src/generated/types.generated.ts')

const content = `// This file is generated by scripts/generate-types.mjs.
// Do not edit manually.

export type SupportedLocale = 'it-IT' | 'en-US' | 'de-DE' | 'es-ES' | 'fr-FR' | 'pt-PT'

export type AuthorRole = 'student' | 'researcher' | 'writer' | 'editor' | 'author'

export type AppFontPreference = 'classic' | 'dyslexic'

export interface AuthorProfile {
  name: string
  role: AuthorRole
  institutionName?: string
  department?: string
  preferredLanguage: SupportedLocale
}

export interface ProjectContributor {
  id: string
  name: string
  role: AuthorRole
  institutionName?: string
  department?: string
  preferredLanguage: SupportedLocale
  addedAt: string
  lastModifiedAt: string
}

export interface ProjectAuthorshipStat {
  authorId: string
  wordCount: number
  percentage: number
}

export interface ProjectManifest {
  format: 'pecie-project'
  formatVersion: string
  projectId: string
  title: string
  createdAt: string
  lastOpenedAt?: string
  appMinVersion: string
  historyMode: 'git-local'
  contentModel: 'markdown-frontmatter'
  cacheModel: 'sqlite-derived'
  defaultExportProfile: string
  language: string
  privacyMode: 'local-first'
  embeddedHistory: boolean
  a11yProfile: 'wcag22-aa'
  schemaUris: {
    manifest: string
    project: string
    binder: string
  }
}

export interface MediaAssetRecord {
  id: string
  relativePath: string
  mimeType: string
  byteSize: number
  sha256: string
  originalFilename: string
  createdAt: string
  kind: 'image'
}

export interface ProjectMetadata {
  title: string
  subtitle?: string
  author: {
    name: string
    role: AuthorRole
  }
  authors?: ProjectContributor[]
  primaryAuthorId?: string
  authorshipStats?: ProjectAuthorshipStat[]
  assets?: MediaAssetRecord[]
  institution?: {
    name: string
    department?: string
  }
  documentKind: 'blank' | 'thesis' | 'paper' | 'book' | 'manual' | 'journal' | 'article' | 'videoScript' | 'screenplay'
  defaultLanguage: string
  defaultBibliographyStyle: string
  projectVisibility: 'private-local'
  containsSensitiveData: boolean
}

export interface BinderNode {
  id: string
  type: 'folder' | 'document'
  title: string
  description?: string
  children?: string[]
  path?: string
  documentId?: string
}

export interface BinderDocument {
  rootId: string
  nodes: BinderNode[]
}

export interface DocumentRecord {
  documentId: string
  binderNodeId: string
  path: string
  title: string
  frontmatter: Record<string, string | boolean | string[]>
  body: string
}

export interface CreateProjectRequest {
  directory: string
  projectName: string
  title: string
  language: SupportedLocale
  template: 'blank' | 'thesis' | 'paper' | 'book' | 'manual' | 'journal' | 'article' | 'videoScript' | 'screenplay'
  authorProfile: AuthorProfile
}

export interface CreateProjectResponse {
  projectPath: string
  manifest: ProjectManifest
  project: ProjectMetadata
  binder: BinderDocument
}

export interface OpenProjectRequest {
  projectPath: string
}

export interface OpenProjectResponse {
  projectPath: string
  manifest: ProjectManifest
  project: ProjectMetadata
  binder: BinderDocument
}

export interface LoadDocumentRequest {
  projectPath: string
  documentId: string
}

export interface LoadDocumentResponse {
  document: DocumentRecord
}

export interface SaveDocumentRequest {
  projectPath: string
  documentId: string
  title: string
  body: string
  authorProfile: AuthorProfile
}

export interface SaveDocumentResponse {
  document: DocumentRecord
  savedAt: string
}

export interface AddBinderNodeRequest {
  projectPath: string
  parentId: string
  nodeType: 'folder' | 'document'
  title?: string
  description?: string
  template?: 'blank' | 'chapter' | 'notes' | 'scene'
  duplicateFromDocumentId?: string
  targetIndex?: number
}

export interface AddBinderNodeResponse {
  binder: BinderDocument
  createdNode: BinderNode
}

export interface MoveBinderNodeRequest {
  projectPath: string
  nodeId: string
  targetParentId: string
  targetIndex: number
}

export interface MoveBinderNodeResponse {
  binder: BinderDocument
}

export interface DeleteBinderNodeRequest {
  projectPath: string
  nodeId: string
}

export interface DeleteBinderNodeResponse {
  binder: BinderDocument
  deletedNodeIds: string[]
}

export interface SearchDocumentsRequest {
  projectPath: string
  query: string
  limit?: number
}

export interface SearchDocumentsResponse {
  results: {
    nodes: Array<{
      nodeId: string
      documentId: string
      title: string
      path: string
      snippet: string
    }>
    content: Array<{
      nodeId: string
      documentId: string
      title: string
      path: string
      snippet: string
    }>
    attachments: Array<{
      relativePath: string
      absolutePath: string
      name: string
      extension: string
      snippet: string
    }>
  }
}

export interface ArchiveProjectRequest {
  projectPath: string
  workspaceDirectory: string
}

export interface ArchiveProjectResponse {
  projectPath: string
}

export interface RestoreProjectRequest {
  projectPath: string
  workspaceDirectory: string
}

export interface RestoreProjectResponse {
  projectPath: string
}

export interface DeleteProjectRequest {
  projectPath: string
}

export interface DeleteProjectResponse {
  deleted: boolean
}

export interface PickDirectoryRequest {
  defaultPath?: string
}

export interface PickDirectoryResponse {
  canceled: boolean
  path?: string
}

export interface PickProjectRequest {
  defaultPath?: string
}

export interface PickProjectResponse {
  canceled: boolean
  path?: string
}

export interface OpenPathRequest {
  path: string
}

export interface OpenPathResponse {
  success: boolean
}

export interface PickFilesRequest {
  defaultPath?: string
  allowMultiple?: boolean
}

export interface PickFilesResponse {
  canceled: boolean
  paths: string[]
}

export interface GetPathDetailsRequest {
  path: string
}

export interface GetPathDetailsResponse {
  name: string
  sizeBytes: number
  isFile: boolean
}

export interface AttachmentRecord {
  name: string
  relativePath: string
  absolutePath: string
  sizeBytes: number
  importedAt: string
  extension: string
}

export interface ListAttachmentsRequest {
  projectPath: string
}

export interface ListAttachmentsResponse {
  attachmentsDirectoryPath: string
  maxFileSizeBytes: number
  items: AttachmentRecord[]
}

export interface ImportAttachmentsRequest {
  projectPath: string
  sourcePaths: string[]
}

export interface ImportAttachmentsResponse {
  attachmentsDirectoryPath: string
  maxFileSizeBytes: number
  imported: AttachmentRecord[]
  skipped: Array<{
    sourcePath: string
    reason: string
  }>
  items: AttachmentRecord[]
}

export interface AttachmentPreviewRequest {
  projectPath: string
  relativePath: string
}

export interface AttachmentPreviewResponse {
  attachment: AttachmentRecord
  preview: {
    kind: 'pdf' | 'epub' | 'html' | 'text' | 'unsupported'
    textContent?: string
    htmlContent?: string
  }
}

export interface AbsorbBinderNodeRequest {
  projectPath: string
  sourceNodeId: string
  targetDocumentId: string
  insertion: 'prepend' | 'append' | 'offset'
  offset?: number
}

export interface AbsorbBinderNodeResponse {
  binder: BinderDocument
  targetDocument: DocumentRecord
  deletedNodeIds: string[]
}

export interface ImportImageAssetRequest {
  projectPath: string
  sourcePath: string
  altText: string
  documentRelativePath: string
}

export interface ImportImageAssetResponse {
  asset: MediaAssetRecord
  markdownSnippet: string
  deduplicated: boolean
}

export interface ExportDocumentRequest {
  projectPath: string
  format: 'pdf' | 'docx' | 'odt' | 'rtf' | 'epub' | 'latex' | 'jats' | 'tei' | 'md' | 'txt'
  outputPath: string
  scope: 'current-document' | 'whole-project'
  documentId?: string
}

export interface ExportDocumentResponse {
  success: boolean
  outputPath?: string
  log: string[]
}

export interface AppSettings {
  workspaceDirectory: string
  locale: SupportedLocale
  theme: 'light' | 'dark' | 'system'
  fontPreference: AppFontPreference
  recentProjectPaths: string[]
  archivedProjectPaths: string[]
  authorProfile: AuthorProfile
  onboardingCompleted: boolean
}

export type AppBootstrapRequest = Record<string, never>

export interface AppBootstrapResponse {
  settings: AppSettings
  defaults: {
    documentsDirectory: string
    defaultWorkspaceDirectory: string
    appDataDirectory: string
  }
  firstRun: boolean
  quickResume?: {
    projectPath: string
    lastEditedSnippet: string
    lastEditedAt: string
  }
}

export interface SaveAppSettingsRequest {
  settings: AppSettings
}

export interface SaveAppSettingsResponse {
  settings: AppSettings
}

export interface LogEventRequest {
  level: 'info' | 'warn' | 'error'
  category: 'renderer' | 'main' | 'project' | 'settings' | 'export' | 'navigation' | 'bug-report'
  event: string
  message: string
  context?: Record<string, string | number | boolean | null>
}

export interface LogEventResponse {
  recorded: boolean
}

export interface ComposeBugReportRequest {
  locale: SupportedLocale
  currentProjectPath?: string
}

export interface ComposeBugReportResponse {
  opened: boolean
  logPath: string
  method: 'system-mail' | 'fallback'
}

export type PrepareUninstallRequest = Record<string, never>

export interface PrepareUninstallResponse {
  success: boolean
  removedPath: string
}

export type IpcContractMap = {
  'settings:bootstrap': {
    request: AppBootstrapRequest
    response: AppBootstrapResponse
  }
  'settings:save': {
    request: SaveAppSettingsRequest
    response: SaveAppSettingsResponse
  }
  'log:event': {
    request: LogEventRequest
    response: LogEventResponse
  }
  'project:create': {
    request: CreateProjectRequest
    response: CreateProjectResponse
  }
  'project:open': {
    request: OpenProjectRequest
    response: OpenProjectResponse
  }
  'document:load': {
    request: LoadDocumentRequest
    response: LoadDocumentResponse
  }
  'document:save': {
    request: SaveDocumentRequest
    response: SaveDocumentResponse
  }
  'binder:add-node': {
    request: AddBinderNodeRequest
    response: AddBinderNodeResponse
  }
  'binder:move-node': {
    request: MoveBinderNodeRequest
    response: MoveBinderNodeResponse
  }
  'binder:delete-node': {
    request: DeleteBinderNodeRequest
    response: DeleteBinderNodeResponse
  }
  'binder:absorb-node': {
    request: AbsorbBinderNodeRequest
    response: AbsorbBinderNodeResponse
  }
  'search:query': {
    request: SearchDocumentsRequest
    response: SearchDocumentsResponse
  }
  'project:archive': {
    request: ArchiveProjectRequest
    response: ArchiveProjectResponse
  }
  'project:restore': {
    request: RestoreProjectRequest
    response: RestoreProjectResponse
  }
  'project:delete': {
    request: DeleteProjectRequest
    response: DeleteProjectResponse
  }
  'path:pickDirectory': {
    request: PickDirectoryRequest
    response: PickDirectoryResponse
  }
  'path:pickProject': {
    request: PickProjectRequest
    response: PickProjectResponse
  }
  'path:pickFiles': {
    request: PickFilesRequest
    response: PickFilesResponse
  }
  'path:getDetails': {
    request: GetPathDetailsRequest
    response: GetPathDetailsResponse
  }
  'path:openInFileManager': {
    request: OpenPathRequest
    response: OpenPathResponse
  }
  'attachment:list': {
    request: ListAttachmentsRequest
    response: ListAttachmentsResponse
  }
  'attachment:import': {
    request: ImportAttachmentsRequest
    response: ImportAttachmentsResponse
  }
  'attachment:preview': {
    request: AttachmentPreviewRequest
    response: AttachmentPreviewResponse
  }
  'image:import-asset': {
    request: ImportImageAssetRequest
    response: ImportImageAssetResponse
  }
  'export:document': {
    request: ExportDocumentRequest
    response: ExportDocumentResponse
  }
  'bug-report:compose': {
    request: ComposeBugReportRequest
    response: ComposeBugReportResponse
  }
  'app:prepareUninstall': {
    request: PrepareUninstallRequest
    response: PrepareUninstallResponse
  }
}
`

await mkdir(dirname(generatedFilePath), { recursive: true })
await writeFile(generatedFilePath, content, 'utf8')
